#!/bin/bash

#
# bash test
# author: kd
#
# Experimenting with a bash script
#

# # # # # # # # # # # # # # # #
# Macros                      #
# # # # # # # # # # # # # # # #

SOURCE_DIRECT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     # While $SOURCE is a symlink, resolve it
     while [ -h "$SOURCE" ]
     do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     echo "$DIR"
}

SOURCE_DIRECT="$(get_script_dir)"
echo -e "three two one let's jam";
ls -la ${SOURCE_DIRECT}/hey;
